export const PostFormActionTypes = {
    SET_PHONE_NUMBER: 'SET_PHONE_NUMBER',
    SET_STATE: 'SET_STATE',
    SET_CITY: 'SET_CITY',
    SET_CATEGORY: 'SET_CATEGORY',
    SET_TITLE: 'SET_TITLE',
    SET_DESCRIPTION: 'SET_DESCRIPTION',
    SET_IMAGES: 'SET_IMAGES',
}