# Generated by Django 3.2.9 on 2021-11-13 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-pub_date']},
        ),
    ]
