export const LOCATION_OPTIONS = [
  {
    value: '美国东部',
    label: '美国东部',
    children: [
      {
        value: '纽约',
        label: '纽约',
        children: [
          { value: '曼哈顿', label: '曼哈顿' },
          { value: '法拉盛', label: '法拉盛' },
          { value: '布鲁伦', label: '布鲁伦' },
          { value: '皇后区', label: '皇后区' },
          { value: '布朗士', label: '布朗士' },
          { value: '长岛', label: '长岛' },
          { value: '史登岛', label: '史登岛' },
          { value: '其他', label: '其他' },
        ],
      },
      { value: '上州', label: '上州' },
      { value: '宾州', label: '宾州' },
      { value: '康州', label: '康州' },
      { value: '麻州', label: '麻州' },
      { value: '新泽西', label: '新泽西' },
      { value: '罗得岛', label: '罗得岛' },
      { value: '缅因州', label: '缅因州' },
      { value: '佛蒙特', label: '佛蒙特' },
      { value: '新罕布什尔', label: '新罕布什尔' },
    ],
  },
  {
    value: '美国西部',
    label: '美国西部',
    children: [
      { value: '洛杉矶', label: '洛杉矶' },
      { value: '南加州', label: '南加州' },
      { value: '犹他', label: '犹他' },
      { value: '内华达', label: '内华达' },
      { value: '蒙大拿', label: '蒙大拿' },
      { value: '俄勒冈', label: '俄勒冈' },
      { value: '爱达荷', label: '爱达荷' },
      { value: '怀俄明', label: '怀俄明' },
      { value: '科罗拉多', label: '科罗拉多' },
      { value: '亚利桑那', label: '亚利桑那' },
      { value: '阿拉斯加', label: '阿拉斯加' },
      { value: '新墨西哥', label: '新墨西哥' },
      { value: '华盛顿州', label: '华盛顿州' },
      { value: '夏威夷', label: '夏威夷' },
    ],
  },
  {
    value: '美国南部',
    label: '美国南部',
    children: [
      { value: '佛州', label: '佛州' },
      { value: '德州', label: '德州' },
      { value: '南卡', label: '南卡' },
      { value: '北卡', label: '北卡' },
      { value: '马里兰', label: '马里兰' },
      { value: '乔治亚', label: '乔治亚' },
      { value: '田纳西', label: '田纳西' },
      { value: '路易斯安娜', label: '路易斯安娜' },
      { value: '肯塔基', label: '肯塔基' },
      { value: '特拉华', label: '特拉华' },
      { value: '密西西比', label: '密西西比' },
      { value: '俄克拉荷马', label: '俄克拉荷马' },
      { value: '阿肯色', label: '阿肯色' },
      { value: '阿拉巴马', label: '阿拉巴马' },
      { value: '弗吉尼亚', label: '弗吉尼亚' },
      { value: '西弗吉尼亚', label: '西弗吉尼亚' },
    ],
  },
  {
    value: '美国中部',
    label: '美国中部',
    children: [
      { value: '伊州', label: '伊州' },
      { value: '俄亥俄', label: '俄亥俄' },
      { value: '密苏里', label: '密苏里' },
      { value: '堪萨斯', label: '堪萨斯' },
      { value: '爱荷华', label: '爱荷华' },
      { value: '密歇根', label: '密歇根' },
      { value: '明尼苏达', label: '明尼苏达' },
      { value: '南达科他', label: '南达科他' },
      { value: '北达科他', label: '北达科他' },
      { value: '印第安纳', label: '印第安纳' },
      { value: '威斯康星', label: '威斯康星' },
      { value: '内布拉斯加', label: '内布拉斯加' },
    ],
  },
];

export const CATEGORY_OPTIONS = [
  {
    value: '招聘求职',
    label: '招聘求职',
    children: [
      { value: '餐饮招聘', label: '餐饮招聘' },
      { value: '美甲招聘', label: '美甲招聘' },
      { value: '按摩招聘', label: '按摩招聘' },
      { value: '文职招聘', label: '文职招聘' },
      { value: '其他招聘', label: '其他招聘' },
    ],
  },
  {
    value: '房屋租售',
    label: '房屋租售',
    children: [
      { value: '房屋出租', label: '房屋出租' },
      { value: '店铺出租', label: '店铺出租' },
      { value: '房产出租', label: '房产出租' },
    ],
  },
  {
    value: '二手买卖',
    label: '二手买卖',
    children: [
      { value: '二手物品', label: '二手物品' },
      { value: '二手汽车', label: '二手汽车' },
      { value: '餐馆用具', label: '餐馆用具' },
    ],
  },
  {
    value: '生意转让',
    label: '生意转让',
    children: [
      { value: '餐馆转让', label: '餐馆转让' },
      { value: '甲店转让', label: '甲店转让' },
      { value: '按摩转让', label: '按摩转让' },
      { value: '其他转让', label: '其他转让' },
    ],
  },
];
