# Generated by Django 3.2.9 on 2021-11-25 16:46

from django.db import migrations
from app._states import STATES


class Migration(migrations.Migration):

    def init_states(apps, schema_editor):
        State = apps.get_model('app', 'State')
        for region, states in STATES.items():
            for state in states:
                s = State(name=state, region=region)
                s.save()

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_states),
    ]
