# Generated by Django 3.2.9 on 2021-12-10 14:20

from django.db import migrations
from app.ny import NY


class Migration(migrations.Migration):

    def init_new_york_city(apps, schema_editor):
        State = apps.get_model('app', 'State')
        City = apps.get_model('app', 'City')
        for city in NY:
            s = State.objects.get(name='纽约')
            c = City(name=city, state=s)
            c.save()

    dependencies = [
        ('app', '0002_auto_20211210_1420'),
    ]

    operations = [
        migrations.RunPython(init_new_york_city),
    ]
