# Generated by Django 3.2.9 on 2021-11-15 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='state_id',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
