# Generated by Django 3.2.9 on 2021-11-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211115_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('recruitment', '招聘求职'), ('house_rental_and_sale', '房屋租售'), ('flea_market', '二手买卖'), ('business_transfer', '生意转让'), ('city_service', '\xa0同城服务')], max_length=50),
        ),
    ]
