# Generated by Django 3.2.9 on 2021-11-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('recruitment', 'Recruitment'), ('house_rental_and_sale', 'House Rental and Sale'), ('flea_market', 'Flea Market'), ('business_transfer', 'Business Transfer'), ('city_service', 'City Service')], max_length=50),
        ),
    ]
