# Generated by Django 3.2.9 on 2021-11-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('construction', 'Construction'), ('manicure', 'Manicure'), ('office', 'Office'), ('massage', 'Massage'), ('other_recruitment', 'Other Recruitment'), ('house_for_rent', 'House for Rent'), ('house_rent_seeking', 'House Rent Seeking'), ('store_rental', 'Store Rental'), ('property_sale', 'Property Sale'), ('used_cars', 'Used Cars'), ('used_goods', 'Used Goods'), ('used_restaurant_stuff', 'Used Restaurant Stuff'), ('car_service', 'Car Service'), ('renovation', 'Renovation'), ('hotel', 'Hotel'), ('lawyer', 'Lawyer'), ('doctor', 'Doctor')], max_length=50),
        ),
    ]
