# Generated by Django 3.2.9 on 2021-11-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='3474407048', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
